Use a patched ogccite/ets-ogcapi-features10 Docker image with additional fixes
Use a patched version of `ogccite/ets-ogcapi-features10:1.8-SNAPSHOT-teamengine-5.4.1`.

Currently, we require the following pull request to be applied:
[Fix global crs codes lookup in discovery collections crs tests](https://github.com/opengeospatial/ets-ogcapi-features10/pull/255)
to the test suite.

This may happen again, hence we're introducing a build step to generate
the required `ogccite/ets-ogcapi-features10` image out of the
`geoserver/ets-ogcapi-features10` fork, using a branch named `geoserver/integration`.

The procedure to maintain that branch is to rebase on top of the upstream
master branch as required, and apply the additional branches with `git merge --no-ff`.

diff --git a/build/cite/Makefile b/build/cite/Makefile
--- a/build/cite/Makefile
+++ b/build/cite/Makefile
@@ -32,6 +32,8 @@ war:	## 					Build the geoserver.war file to use for testing and place it in ./g
 	@$(MAKE) build-war
 	@$(MAKE) copy-war
 
+# calls build-ets-image and build-geoserver-image
+# the CI job may call them independently for the sake of using separate job steps
 .PHONY: build
 build: ##	suite=<suite>				Build the GeoServer Docker Image for the Environment.
 ifndef suite
@@ -39,9 +41,32 @@ ifndef suite
 	@$(MAKE) help
 	@exit 1
 endif
+	@$(MAKE) build-ets-image
+	@$(MAKE) build-geoserver-image
+
+# preparing the geoserver image is performed with docker-compose build including $suite/compose-override.yml
+.PHONY: build-geoserver-image
+build-geoserver-image:
+ifndef suite
+	@echo "Error: suite is not specified. Please specify the suite to build the GeoServer Docker image for."
+	@exit 1
+endif
 	@echo Building the GeoServer Docker Image for the $(suite) test suite
 	@docker compose -f compose.yml -f ./$(suite)/compose.override.yml \
 	  build --no-cache --build-arg SOURCE_FILE=${war_url} geoserver
+
+# If there's a $suite/build-ets.sh file calls it, otherwise exists silently
+.PHONY: build-ets-image
+build-ets-image:
+ifndef suite
+	@echo "Error: suite is not specified. Please specify the suite to build the GeoServer Docker image for."
+	@exit 1
+endif
+	@if [ -f "$(suite)/build-ets.sh" ]; then \
+		(cd $(suite) && ./build-ets.sh); \
+	else \
+		echo "$(suite) has no special script to build the ETS docker image."; \
+	fi
 
 .PHONY: test
 test: ##	suite=<suite>				Run the Test Suite with teamengine and GeoServer on docker compose.
@@ -282,7 +307,7 @@ print-logs:
 
 # Used in CI/CD to print which services and images are going to be run
 # Requires `jq`, comes pre-installed in github actions `ubuntu-latest`
-.PHONY: print-docker-compose-services
+.PHONY: print-services
 print-services: ### suite=<suite>			Print the service names and docker images used for a given suite
 ifndef suite
 	@echo "Error: suite is not specified."
