[GEOS-11828] Random test failures in WFS 2.0 CITE tests, on Github actions

diff --git a/.github/workflows/cite.yml b/.github/workflows/cite.yml
--- a/.github/workflows/cite.yml
+++ b/.github/workflows/cite.yml
@@ -109,7 +109,21 @@ jobs:
         working-directory: build/cite
         run: |
           chmod o+w logs
-          make test suite=${{ matrix.suite }}
+          # WFS 2.0 lock tests can randomly fail due to timing issues, retry them
+          if [ "${{ matrix.suite }}" = "wfs20" ]; then
+            MAX_RETRIES=5
+            COUNT=0
+            until make test suite=${{ matrix.suite }}; do
+              COUNT=$((COUNT+1))
+              if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
+                echo "WFS 2.0 tests failed after $COUNT attempts."
+                exit 1
+              fi
+              echo "Retrying WFS 2.0... attempt $((COUNT+1)) of $MAX_RETRIES"
+            done
+          else
+            make test suite=${{ matrix.suite }}
+          fi
 
       - name: Print full failures report
         if: always()
